window.QUIZ_DATA = [
  {
    "id": "Level 1",
    "title": "Identify the State",
    "description": "Match each dance to the correct Indian state.",
    "questions": [
      { "question": "Bihu dance belongs to which state?", "options": ["Assam", "Punjab", "Gujarat", "Bihar"], "answer": 0 },
      { "question": "Garba dance belongs to which state?", "options": ["Gujarat", "Rajasthan", "Maharashtra", "Haryana"], "answer": 0 },
      { "question": "Ghoomar dance belongs to which state?", "options": ["Rajasthan", "Punjab", "Uttar Pradesh", "Bihar"], "answer": 0 },
      { "question": "Bhangra dance belongs to which state?", "options": ["Punjab", "Gujarat", "Odisha", "Assam"], "answer": 0 },
      { "question": "Lavani dance belongs to which state?", "options": ["Maharashtra", "Karnataka", "Tamil Nadu", "Kerala"], "answer": 0 },
      { "question": "Yakshagana belongs to which state?", "options": ["Karnataka", "Gujarat", "Assam", "Bihar"], "answer": 0 },
      { "question": "Karagattam belongs to which state?", "options": ["Tamil Nadu", "Kerala", "Odisha", "Goa"], "answer": 0 },
      { "question": "Fugdi dance belongs to which state?", "options": ["Goa", "Punjab", "Rajasthan", "Assam"], "answer": 0 },
      { "question": "Panthi dance belongs to which state?", "options": ["Chhattisgarh", "Bihar", "Gujarat", "Haryana"], "answer": 0 },
      { "question": "Cheraw (Bamboo Dance) belongs to which state?", "options": ["Mizoram", "Manipur", "Nagaland", "Sikkim"], "answer": 0 },
      { "question": "Ras Leela belongs to which state?", "options": ["Manipur", "Punjab", "Assam", "Haryana"], "answer": 0 },
      { "question": "Rouf dance belongs to which state?", "options": ["Jammu & Kashmir", "Himachal Pradesh", "Punjab", "Rajasthan"], "answer": 0 },
      { "question": "Nati dance belongs to which state?", "options": ["Himachal Pradesh", "Uttarakhand", "Punjab", "Haryana"], "answer": 0 },
      { "question": "Khoria dance belongs to which state?", "options": ["Haryana", "Punjab", "Gujarat", "Rajasthan"], "answer": 0 },
      { "question": "Kalbelia dance belongs to which state?", "options": ["Rajasthan", "Gujarat", "Bihar", "Odisha"], "answer": 0 },
      { "question": "Matki dance belongs to which state?", "options": ["Madhya Pradesh", "Rajasthan", "Gujarat", "Punjab"], "answer": 0 },
      { "question": "Koli dance belongs to which state?", "options": ["Maharashtra", "Kerala", "Goa", "Tamil Nadu"], "answer": 0 },
      { "question": "Chholiya dance belongs to which state?", "options": ["Uttarakhand", "Himachal Pradesh", "Punjab", "Haryana"], "answer": 0 },
      { "question": "Karma dance belongs to which state?", "options": ["Madhya Pradesh", "Gujarat", "Punjab", "Bihar"], "answer": 0 },
      { "question": "Singhi Chham belongs to which state?", "options": ["Sikkim", "Nagaland", "Assam", "Arunachal Pradesh"], "answer": 0 },
      { "question": "Maruni dance belongs to which state?", "options": ["Sikkim", "Mizoram", "Assam", "Bihar"], "answer": 0 },
      { "question": "Bardo Chham belongs to which state?", "options": ["Arunachal Pradesh", "Sikkim", "Manipur", "Nagaland"], "answer": 0 },
      { "question": "Ponung dance belongs to which state?", "options": ["Arunachal Pradesh", "Assam", "Bihar", "Mizoram"], "answer": 0 },
      { "question": "Deodhani dance belongs to which state?", "options": ["Assam", "Odisha", "Gujarat", "Haryana"], "answer": 0 },
      { "question": "Bagurumba dance belongs to which state?", "options": ["Assam", "Bihar", "Goa", "Kerala"], "answer": 0 },
      { "question": "Nautanki belongs to which state?", "options": ["Uttar Pradesh", "Rajasthan", "Bihar", "Haryana"], "answer": 0 },
      { "question": "Charkula dance belongs to which state?", "options": ["Uttar Pradesh", "Punjab", "Gujarat", "Bihar"], "answer": 0 },
      { "question": "Mayur dance belongs to which state?", "options": ["Uttar Pradesh", "Rajasthan", "Gujarat", "Haryana"], "answer": 0 },
      { "question": "Thiruvathirakali belongs to which state?", "options": ["Kerala", "Tamil Nadu", "Karnataka", "Goa"], "answer": 0 },
      { "question": "Ottamthullal belongs to which state?", "options": ["Kerala", "Gujarat", "Odisha", "Assam"], "answer": 0 },
      { "question": "Veeragase belongs to which state?", "options": ["Karnataka", "Kerala", "Gujarat", "Assam"], "answer": 0 },
      { "question": "Dollu Kunitha belongs to which state?", "options": ["Karnataka", "Punjab", "Rajasthan", "Gujarat"], "answer": 0 },
      { "question": "Tippani dance belongs to which state?", "options": ["Gujarat", "Punjab", "Odisha", "Bihar"], "answer": 0 },
      { "question": "Sua Nacha belongs to which state?", "options": ["Chhattisgarh", "Bihar", "Odisha", "Punjab"], "answer": 0 },
      { "question": "Jhumar belongs to which state?", "options": ["Punjab", "Gujarat", "Kerala", "Assam"], "answer": 0 },
      { "question": "Paika dance belongs to which state?", "options": ["Odisha", "Bihar", "Punjab", "Haryana"], "answer": 0 },
      { "question": "Chang Lo dance belongs to which state?", "options": ["Nagaland", "Mizoram", "Sikkim", "Assam"], "answer": 0 },
      { "question": "Zeliang dance belongs to which state?", "options": ["Nagaland", "Manipur", "Assam", "Sikkim"], "answer": 0 },
      { "question": "Jat-Jatin dance belongs to which state?", "options": ["Bihar", "Gujarat", "Haryana", "Punjab"], "answer": 0 },
      { "question": "Jhijhiya dance belongs to which state?", "options": ["Bihar", "Assam", "Gujarat", "Rajasthan"], "answer": 0 },
      { "question": "Bidesia dance belongs to which state?", "options": ["Bihar", "Punjab", "Assam", "Odisha"], "answer": 0 },
      { "question": "Gangaur dance belongs to which state?", "options": ["Rajasthan", "Gujarat", "Punjab", "Haryana"], "answer": 0 },
      { "question": "Gambhira dance belongs to which state?", "options": ["West Bengal", "Assam", "Odisha", "Bihar"], "answer": 0 },
      { "question": "Dumhal dance belongs to which state?", "options": ["Jammu & Kashmir", "Punjab", "Himachal Pradesh", "Haryana"], "answer": 0 },
      { "question": "Kummi dance belongs to which state?", "options": ["Tamil Nadu", "Kerala", "Karnataka", "Goa"], "answer": 0 },
      { "question": "Kolattam dance belongs to which state?", "options": ["Tamil Nadu", "Gujarat", "Punjab", "Assam"], "answer": 0 },
      { "question": "Giddha dance belongs to which state?", "options": ["Punjab", "Haryana", "Rajasthan", "Bihar"], "answer": 0 },
      { "question": "Chhau dance is mainly from which state?", "options": ["Odisha", "Gujarat", "Punjab", "Haryana"], "answer": 0 },
      { "question": "Dandiya Raas belongs to which state?", "options": ["Gujarat", "Rajasthan", "Maharashtra", "Punjab"], "answer": 0 },
      { "question": "Phag dance belongs to which state?", "options": ["Haryana", "Punjab", "Rajasthan", "Gujarat"], "answer": 0 }
    ]
  },
  {
    "id": "Level 2",
    "title": "Identify the Dance",
    "description": "Choose the correct dance for the state named in each question.",
    "questions": [
      { "question": "Which dance belongs to Assam?", "options": ["Bihu", "Garba", "Ghoomar", "Lavani"], "answer": 0 },
      { "question": "Which dance belongs to Punjab?", "options": ["Bhangra", "Cheraw", "Yakshagana", "Rouf"], "answer": 0 },
      { "question": "Which dance belongs to Gujarat?", "options": ["Garba", "Bihu", "Giddha", "Panthi"], "answer": 0 },
      { "question": "Which dance belongs to Kerala?", "options": ["Thiruvathirakali", "Ghoomar", "Jhumar", "Matki"], "answer": 0 },
      { "question": "Which dance belongs to Tamil Nadu?", "options": ["Karagattam", "Fugdi", "Paika", "Rouf"], "answer": 0 },
      { "question": "Which dance belongs to Karnataka?", "options": ["Yakshagana", "Bidesia", "Charkula", "Giddha"], "answer": 0 },
      { "question": "Which dance belongs to Goa?", "options": ["Fugdi", "Panthi", "Kalbelia", "Khoria"], "answer": 0 },
      { "question": "Which dance belongs to Chhattisgarh?", "options": ["Panthi", "Garba", "Ras Leela", "Yakshagana"], "answer": 0 },
      { "question": "Which dance belongs to Maharashtra?", "options": ["Lavani", "Bihu", "Paika", "Phag"], "answer": 0 },
      { "question": "Which dance belongs to Manipur?", "options": ["Ras Leela", "Ghoomar", "Jhumar", "Kalbelia"], "answer": 0 },
      { "question": "Which dance belongs to Mizoram?", "options": ["Cheraw", "Giddha", "Lavani", "Garba"], "answer": 0 },
      { "question": "Which dance belongs to Rajasthan?", "options": ["Ghoomar", "Bihu", "Yakshagana", "Rouf"], "answer": 0 },
      { "question": "Which dance belongs to Haryana?", "options": ["Khoria", "Garba", "Fugdi", "Panthi"], "answer": 0 },
      { "question": "Which dance belongs to Himachal Pradesh?", "options": ["Nati", "Bhangra", "Garba", "Lavani"], "answer": 0 },
      { "question": "Which dance belongs to Jammu & Kashmir?", "options": ["Rouf", "Garba", "Kummi", "Bihu"], "answer": 0 },
      { "question": "Which dance belongs to West Bengal?", "options": ["Gambhira", "Garba", "Yakshagana", "Fugdi"], "answer": 0 },
      { "question": "Which dance belongs to Odisha?", "options": ["Paika", "Garba", "Jhumar", "Lavani"], "answer": 0 },
      { "question": "Which dance belongs to Uttar Pradesh?", "options": ["Nautanki", "Cheraw", "Giddha", "Yakshagana"], "answer": 0 },
      { "question": "Which dance belongs to Uttarakhand?", "options": ["Chholiya", "Garba", "Lavani", "Panthi"], "answer": 0 },
      { "question": "Which dance belongs to Sikkim?", "options": ["Singhi Chham", "Giddha", "Rouf", "Bihu"], "answer": 0 },
      { "question": "Which dance belongs to Arunachal Pradesh?", "options": ["Ponung", "Garba", "Bhangra", "Fugdi"], "answer": 0 },
      { "question": "Which dance belongs to Nagaland?", "options": ["Chang Lo", "Ghoomar", "Lavani", "Panthi"], "answer": 0 },
      { "question": "Which dance belongs to Bihar?", "options": ["Jat-Jatin", "Garba", "Yakshagana", "Cheraw"], "answer": 0 },
      { "question": "Which dance belongs to Madhya Pradesh?", "options": ["Matki", "Bihu", "Rouf", "Fugdi"], "answer": 0 },
      { "question": "Which dance belongs to Jharkhand?", "options": ["Paika", "Giddha", "Garba", "Lavani"], "answer": 0 },
      { "question": "Which dance belongs to Telangana?", "options": ["Perini Shivatandavam", "Ghoomar", "Bhangra", "Cheraw"], "answer": 0 },
      { "question": "Which dance belongs to Kerala?", "options": ["Ottamthullal", "Garba", "Bihu", "Khoria"], "answer": 0 },
      { "question": "Which dance belongs to Karnataka?", "options": ["Dollu Kunitha", "Panthi", "Rouf", "Jat-Jatin"], "answer": 0 },
      { "question": "Which dance belongs to Rajasthan?", "options": ["Kalbelia", "Garba", "Cheraw", "Fugdi"], "answer": 0 },
      { "question": "Which dance belongs to Punjab?", "options": ["Giddha", "Bihu", "Lavani", "Yakshagana"], "answer": 0 },
      { "question": "Which dance belongs to Gujarat?", "options": ["Dandiya Raas", "Rouf", "Bihu", "Khoria"], "answer": 0 },
      { "question": "Which dance belongs to Tamil Nadu?", "options": ["Kummi", "Garba", "Panthi", "Bhangra"], "answer": 0 },
      { "question": "Which dance belongs to Maharashtra?", "options": ["Koli Dance", "Bihu", "Paika", "Fugdi"], "answer": 0 },
      { "question": "Which dance belongs to West Bengal?", "options": ["Chhau", "Garba", "Giddha", "Rouf"], "answer": 0 },
      { "question": "Which dance belongs to Odisha?", "options": ["Chhau", "Bhangra", "Khoria", "Garba"], "answer": 0 },
      { "question": "Which dance belongs to Assam?", "options": ["Bagurumba", "Garba", "Lavani", "Rouf"], "answer": 0 },
      { "question": "Which dance belongs to Goa?", "options": ["Dhalo", "Bihu", "Yakshagana", "Khoria"], "answer": 0 },
      { "question": "Which dance belongs to Chhattisgarh?", "options": ["Raut Nacha", "Garba", "Ghoomar", "Fugdi"], "answer": 0 },
      { "question": "Which dance belongs to Jharkhand?", "options": ["Jhumar", "Garba", "Bihu", "Lavani"], "answer": 0 },
      { "question": "Which dance belongs to Haryana?", "options": ["Phag", "Bihu", "Garba", "Yakshagana"], "answer": 0 },
      { "question": "Which dance belongs to Himachal Pradesh?", "options": ["Chamba Dance", "Garba", "Panthi", "Rouf"], "answer": 0 },
      { "question": "Which dance belongs to Sikkim?", "options": ["Maruni", "Giddha", "Garba", "Fugdi"], "answer": 0 },
      { "question": "Which dance belongs to Nagaland?", "options": ["Zeliang", "Ghoomar", "Lavani", "Panthi"], "answer": 0 },
      { "question": "Which dance belongs to Arunachal Pradesh?", "options": ["Popir", "Garba", "Rouf", "Giddha"], "answer": 0 },
      { "question": "Which dance belongs to Manipur?", "options": ["Lai Haraoba", "Bhangra", "Garba", "Yakshagana"], "answer": 0 },
      { "question": "Which dance belongs to Punjab?", "options": ["Jhumar", "Bihu", "Cheraw", "Lavani"], "answer": 0 },
      { "question": "Which dance belongs to Mizoram?", "options": ["Bamboo Dance", "Garba", "Khoria", "Rouf"], "answer": 0 },
      { "question": "Which dance belongs to Kerala?", "options": ["Kaikottikali", "Bihu", "Lavani", "Panthi"], "answer": 0 },
      { "question": "Which dance belongs to Karnataka?", "options": ["Veeragase", "Garba", "Fugdi", "Jat-Jatin"], "answer": 0 },
      { "question": "Which dance belongs to Madhya Pradesh?", "options": ["Karma", "Garba", "Bihu", "Rouf"], "answer": 0 }
    ]
  },
  {
    "id": "Level 3",
    "title": "True or False",
    "description": "Read each statement and decide whether it is true or false.",
    "questions": [
      { "question": "Bihu belongs to Assam.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Garba belongs to Gujarat.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Bhangra belongs to Punjab.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Lavani belongs to Maharashtra.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Ghoomar belongs to Rajasthan.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Yakshagana belongs to Karnataka.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Rouf belongs to Jammu & Kashmir.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Nati belongs to Himachal Pradesh.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Khoria belongs to Haryana.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Cheraw belongs to Mizoram.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Ras Leela belongs to Manipur.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Chhau dance is from Odisha.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Paika dance belongs to Odisha.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Kummi belongs to Tamil Nadu.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Karagattam belongs to Tamil Nadu.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Dollu Kunitha belongs to Karnataka.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Fugdi belongs to Goa.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Panthi belongs to Chhattisgarh.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Jhumar belongs to Punjab.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Kalbelia belongs to Rajasthan.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Bidesia belongs to Bihar.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Matki belongs to Madhya Pradesh.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Koli dance belongs to Maharashtra.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Chholiya belongs to Uttarakhand.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Deodhani belongs to Assam.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Bagurumba belongs to Assam.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Giddha belongs to Punjab.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Gangaur belongs to Rajasthan.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Gambhira belongs to West Bengal.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Dumhal belongs to Jammu & Kashmir.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Singhi Chham belongs to Sikkim.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Maruni belongs to Sikkim.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Bardo Chham belongs to Arunachal Pradesh.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Ponung belongs to Arunachal Pradesh.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Popir belongs to Arunachal Pradesh.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Charkula belongs to Uttar Pradesh.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Nautanki belongs to Uttar Pradesh.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Thiruvathirakali belongs to Kerala.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Ottamthullal belongs to Kerala.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Veeragase belongs to Karnataka.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Tippani belongs to Gujarat.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Sua Nacha belongs to Chhattisgarh.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Paika belongs to Jharkhand.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Chang Lo belongs to Nagaland.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Zeliang belongs to Nagaland.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Jat-Jatin belongs to Bihar.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Jhijhiya belongs to Bihar.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Karma dance belongs to Madhya Pradesh.", "options": ["True", "False"], "answer": 0, "type": "boolean" },
      { "question": "Gambhira belongs to Assam.", "options": ["True", "False"], "answer": 1, "type": "boolean" },
      { "question": "Nati belongs to Uttarakhand.", "options": ["True", "False"], "answer": 1, "type": "boolean" }
    ]
  }
]
;
